/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_parc_pss_SchedulerInterface */

#ifndef _Included_com_parc_pss_SchedulerInterface
#define _Included_com_parc_pss_SchedulerInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_parc_pss_SchedulerInterface
 * Method:    Scheduler
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_parc_pss_SchedulerInterface_Scheduler
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_parc_pss_SchedulerInterface
 * Method:    MultisiteScheduler
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_parc_pss_SchedulerInterface_MultisiteScheduler
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
